title: Active TLS Fingerprinting

author: Markus Sosnowski

description: >-
  Characterizing TLS Server Deployments at Scale
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://active-tls-fingerprinting.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  syncall

header_pages:
  - pages/data.md
  - pages/pipeline.md

# Build settings
remote_theme: tumi8/tumi8-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
